### ISSUE TITLE
The numbers on the main numpad are cut off

### ISSUE THREAD

**Issue by microfracture** [bmelnychuk/outlay#2]
**Environment**
* Android 5.1.1
* LG K7
* Outlay 1.1.3

**Expected Result**
The main numpad should display correctly.

**Actual Result**
The numbers on the main screen's numpad do not display correctly and are all cut off at the bottom. 

However, The rest of the application operates as intended.

**Screenshot**

![screenshot_2017-03-20-20-47-57](https://cloud.githubusercontent.com/assets/11038831/24128042/a0f05fd2-0daf-11e7-8f66-a2e3cc05f792.png)

**Comment by bmelnychuk** [comment]
Thanks for posting. Looks like I did not try it on devices with smaller screens

**Comment by bmelnychuk** [comment]
Sorry for long delay, it's finally fixed
